app = "todol"
primary_region = "iad"
console_command = "/app/bin/rails console"

[build]
  [build.args]
    RAILS_ENV = "production"
    NODE_ENV = "production"

[env]
  PORT = "8080"
  RAILS_LOG_TO_STDOUT = "enabled"
  RAILS_SERVE_STATIC_FILES = "enabled"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
