default: &default
  config_path: # config_paths are always loaded, unless blanked (ref: https://github.com/oldmoe/litestack/blob/master/lib/litestack/litesupport.rb#L241)
  sync: 1

development:
  <<: *default
  path: db/development_litecache.sqlite3

test:
  <<: *default
  path: db/test_litecache.sqlite3

production:
  <<: *default
  path: db/production_litecache.sqlite3
